# Generated by Django 2.2.5 on 2019-10-06 19:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_category', models.CharField(max_length=20)),
                ('text_title', models.CharField(max_length=70)),
                ('text_desc', models.CharField(max_length=200)),
                ('text_body', models.TextField()),
                ('pub_date', models.DateField(default=datetime.date.today, verbose_name='date published')),
            ],
        ),
    ]
