# Generated by Django 2.2.5 on 2019-10-06 20:14

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text_body',
            field=martor.models.MartorField(),
        ),
    ]
