# Generated by Django 2.2.5 on 2019-10-07 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191006_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text_category',
            field=models.CharField(choices=[('DE', 'Design'), ('LF', 'Life'), ('OF', 'Off Topic')], default='DE', max_length=2),
        ),
    ]
